#!/bin/bash
echo -e 'This is a script file.'

wget https://github.com/MilenaValentini/TRM_Dati/blob/main/Nemo_6670.dat
ls
echo "Be careful what file you want to select"
program(){
echo "Select your file"
read FILE
echo $FILE
echo
echo "The file $FILE will be analyzed"
python3 analyze_data.py $FILE mio_file_output.txt
python3 ex_pro.py
}

