#!/bin/bash
echo -e 'This is a script file.'

wget https://raw.githubusercontent.com/MilenaValentini/TRM_Dati/main/Nemo_6670.dat
ls
echo "Be careful what file you want to select"
program(){
echo "Select your file"
read FILE
echo "Rename your file if you want, otherwise digit the same name"
read FILE1
if [ FILE1 == '' ]; then
  FILE1 = FILE
else
  FILE1 = FILE
fi
echo
echo "The file $FILE will be analyzed"
python3 ex_pro.py $FILE $FILE1
}

